# Generated by Django 5.0.7 on 2024-08-05 23:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='enunciado',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
