# Generated by Django 5.0.7 on 2024-08-11 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_enunciado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemEnunciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_enunciado/')),
                ('posicao', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('disciplina', models.CharField(max_length=255)),
                ('gabarito', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='imagemenunciado',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_enunciado', to='questions.questao'),
        ),
    ]
