# Generated by Django 5.0.7 on 2024-08-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_imagemenunciado_questao_delete_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_questao/'),
        ),
    ]
