# Generated by Django 5.0.7 on 2024-08-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questao_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='imagem',
        ),
    ]
